### PR TITLE
update group to execgroup, to match execuser

### PR DESCRIPTION
**Pull request by BobVanB**
More something like this. Greetz

### CODE REVIEW

**Comment by BobVanB** [comment]
@carlossg Can you comment on this pull request?
Feature could be much appreciated.

**Comment by carlossg** [comment]
well, you are renaming parameters that would break existing installations, so that's a no-no
also for some reason the travis build is failing

**Comment by BobVanB** [comment]
@carlossg I can live with the argument of not wanting to change parameter names.
As for the broken build, it was not inside my code. Don't know if i can fix it, but i will give it a try.

**Comment by BobVanB** [comment]
Build failure:
`An error occurred while installing nokogiri (1.7.0.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.7.0.1'` succeeds before bundling.
The command "eval bundle install --jobs=3 --retry=3" failed 3 times.
The command "bundle install --jobs=3 --retry=3" failed and exited with 5 during .
Your build has been stopped.`

**Comment by BobVanB** [comment]
Ping

**Comment by BobVanB** [comment]
@carlossg can you do something?

**Comment by BobVanB** [comment]
@carlossg Is this project dead?

**Comment by carlossg** [comment]
Yes, some modules have been forked to voxpupuli

**Comment by BobVanB** [comment]
Dead

**Pull request closed without merging**
