### PR TITLE
Remove undefined variable access

### PR DESCRIPTION
**Pull request by dominikschulz**
This PR tries to work around some issues with strict_variables = true

### CODE REVIEW

**Comment by carlossg** [comment]
lint is failing

schedule was added in #46 mentioning that it shouldn't be in the parameters

**Comment by dominikschulz** [comment]
I'll fix the lint check and check on the metaparams for the future parser. But this parameter didn't work for us with the future parser enabled.

**Comment by carlossg** [comment]
ping @robbat2

**Comment by rvincentatprokarmadotcom** [comment]
I think the problem is that all branches of a selector are evaluated.  I've submitted another patch that converts the selector to an if statement, and it passes tests.

**Comment by robbat2** [comment]
If you don't pass schedule down to the resource, the resource is always applied, which is not desired.

Has the lint changed, that metaparams must now be declared as well?

**Comment by rvincentatprokarmadotcom** [comment]
See https://github.com/maestrodev/puppet-wget/pull/64 for an approach that passes tests.

**Comment by robbat2** [comment]
+1 on #64

**Comment by rvincentatprokarmadotcom** [comment]
Better approach in #66

**Comment by carlossg** [comment]
closing for #66

**Pull request closed without merging**
