### PR TITLE
Added `destination_dir` parameter to allow for iterating over arrays

### PR DESCRIPTION
**Pull request by seanscottking**
See original feature request here: https://github.com/maestrodev/puppet-wget/issues/51

This modification allows you to iterate over an array of URLs and wget them all to one directory.

Use this for an example use case. It's copy/pasteable (about 4MB of files). It can potentially simplify lots of code for users of your module. This currently has to be done with 4 separate declarations of `wget::fetch { 'http://url': destination => '/path' }`.
```puppet
  $manyfiles = [
    'https://www.kernel.org/pub/linux/kernel/v1.0/linux-1.0.tar.bz2',
    'https://www.kernel.org/pub/linux/kernel/v1.0/linux-1.0.tar.gz',
    'https://www.kernel.org/pub/linux/kernel/v1.0/linux-1.0.tar.sign',
    'https://www.kernel.org/pub/linux/kernel/v1.0/linux-1.0.tar.xz',
  ]

  wget::fetch { $manyfiles:
    destination_dir => '/tmp/',
  }
```

And here is another way it has improved. Given the most simple of example of using your module, just downloading a single file, you no longer have to specify the filename. It just takes the file's name of the URL. Looks a lot cleaner imho.
```puppet
  wget::fetch { 'https://www.kernel.org/pub/linux/kernel/v1.0/linux-1.0.tar.bz2':
    destination_dir => '/tmp/',
  }
```

### CODE REVIEW

**Comment by carlossg** [comment]
I think it would be more user friendly if it checks id $destination is a dir and then changes behavior, instead of adding a new parameter

**Comment by seanscottking** [comment]
I agree, I didn't want to cause that much disruption to `$destination` though. Backwards compatibility is a real concern. We can't account for all the different ways people use this module.

But I'll get to work on $destination just to see how it turns out. Do you have any ideas on how to approach that? It's a little tricky, for example if user specifies `destination => /my/path`, and `/my/path` does not exist yet, it's impossible to determine whether the user intended to provide a file or a path.

**Comment by carlossg** [comment]
if it doesn't exist then it is a file, as it was before

**Comment by seanscottking** [comment]
GitHub closed this because I renamed the branch on my fork. Maybe it's a good thing since we are going in a different direction. I'll open a new PR and reference issue #51

**Pull request closed without merging**
